"""empty message

Revision ID: 2753c6a0d544
Revises: 
Create Date: 2023-02-06 14:58:53.171156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2753c6a0d544'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('user',
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chore',
    sa.Column('chore_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chore_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chore')
    op.drop_table('user')
    op.drop_table('group')
    # ### end Alembic commands ###
