"""chore time migration back

Revision ID: ede71a51509b
Revises: 
Create Date: 2023-02-07 17:10:49.971660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede71a51509b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('household_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('household_id')
    )
    op.create_table('member',
    sa.Column('member_name', sa.String(), nullable=True),
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.household_id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('chore',
    sa.Column('chore_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ),
    sa.PrimaryKeyConstraint('chore_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chore')
    op.drop_table('member')
    op.drop_table('household')
    # ### end Alembic commands ###
